class ForsetiLevels:
    TRACE = "TRACE"
    DEBUG = "DEBUG"
    DEBUG_SQL = "DEBUG_SQL"    
    DEBUG_API = "DEBUG_API"    
    DEBUG_CACHE = "DEBUG_CACHE"

    INFO = "INFO"  
    NOTICE = "NOTICE"          

    WARNING = "WARNING"        
    DEPRECATION = "DEPRECATION"
    CONFIG_WARNING = "CONFIG_WARNING"

    ERROR = "ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AUTH_ERROR = "AUTH_ERROR"  
    DB_ERROR = "DB_ERROR"      
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

    CRITICAL = "CRITICAL"      
    SYSTEM_FAILURE = "SYSTEM_FAILURE"
    DATA_LOSS = "DATA_LOSS"    

    OFF = "OFF"    
